package com.example.pi_web;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MonCompte_design extends CssLayout {
	protected com.vaadin.ui.VerticalLayout bandeau;
	protected com.vaadin.ui.Button button_retour;
	protected com.vaadin.ui.TabSheet onglets;
	protected com.vaadin.ui.VerticalLayout onglet_planningDefenses;
	protected com.vaadin.ui.FormLayout form_etudiant;
	protected com.vaadin.ui.Label label_nom;
	protected com.vaadin.ui.TextField tf_nom;
	protected com.vaadin.ui.TextField tf_prenom;
	protected com.vaadin.ui.TextField tf_tel;
	protected com.vaadin.ui.TextField tf_mail;
	protected com.vaadin.ui.PasswordField mdp_actuel;
	protected com.vaadin.ui.PasswordField mdp_nouveau;
	protected com.vaadin.ui.PasswordField mdp_confirmation;
	protected com.vaadin.ui.Button button_confirmer;

	public MonCompte_design() {
		Design.read(this);
	}
}
