package ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class PublicDefenses_design extends CssLayout
{
    protected com.vaadin.ui.VerticalLayout bandeau;
    protected com.vaadin.ui.Button button_connexion;
    protected com.vaadin.ui.TabSheet onglets;
    protected com.vaadin.ui.VerticalLayout onglet_planningDefenses;
    protected com.vaadin.ui.Table tab_defenses;
    protected com.vaadin.ui.Table tab_technologies;

    public PublicDefenses_design()
    {
        Design.read(this);
    }
}
