-- DROP TABLE

DROP TABLE PermissionTable CASCADE CONSTRAINTS;
DROP TABLE RoleTable CASCADE CONSTRAINTS;
DROP TABLE Utilisateur CASCADE CONSTRAINTS;
DROP TABLE SuiviEcheance CASCADE CONSTRAINTS;
DROP TABLE Defense CASCADE CONSTRAINTS;
DROP TABLE Technologie CASCADE CONSTRAINTS;
DROP TABLE Stage CASCADE CONSTRAINTS;
DROP TABLE PropositionStage CASCADE CONSTRAINTS;
DROP TABLE Evaluation CASCADE CONSTRAINTS;
DROP TABLE Critere CASCADE CONSTRAINTS;
DROP TABLE LieuStage CASCADE CONSTRAINTS;
DROP TABLE TFE CASCADE CONSTRAINTS;
DROP TABLE Echeance CASCADE CONSTRAINTS;

-- DROP SEQUENCE

DROP SEQUENCE seq_permission;
DROP SEQUENCE seq_Role;
DROP SEQUENCE seq_Utilisateur;
DROP SEQUENCE seq_SuiviEcheance;
DROP SEQUENCE seq_Defense;
DROP SEQUENCE seq_Technologie;
DROP SEQUENCE seq_Stage;
DROP SEQUENCE seq_PropositionStage;
DROP SEQUENCE seq_Evaluation;
DROP SEQUENCE seq_Critere;
DROP SEQUENCE seq_LieuStage;
DROP SEQUENCE seq_TFE;
DROP SEQUENCE seq_Echeance;

-- DROP TRIGGER INCREMENT SEQUENCE

DROP TRIGGER id_gen_Permission;
DROP TRIGGER id_gen_Role;
DROP TRIGGER id_gen_Utilisateur;
DROP TRIGGER id_gen_SuiviEcheance;
DROP TRIGGER id_gen_Defense;
DROP TRIGGER id_gen_Technologie;
DROP TRIGGER id_gen_Stage;
DROP TRIGGER id_gen_PropositionStage;
DROP TRIGGER id_gen_Evaluation;
DROP TRIGGER id_gen_Critere;
DROP TRIGGER id_gen_LieuStage;
DROP TRIGGER id_gen_TFE;
DROP TRIGGER id_gen_Echeance